---
language: node_js

node_js:
  - '10.15.3'

services:
  - docker

# before_cache:
#  - >
#    mkdir -p $HOME/docker && docker images -a --filter='dangling=false' --format '{{.Repository}}:{{.Tag}} {{.ID}}'
#    | xargs -n 2 -t sh -c 'test -e $HOME/docker/$1.tar.gz || docker save $0 | gzip -2 > $HOME/docker/$1.tar.gz'


# cache:
#  bundler: true
#  directories:
#    - $HOME/docker


before_install:
# - if [[ -d $HOME/docker ]]; then ls $HOME/docker/*.tar.gz | xargs -I {file} sh -c "zcat {file} | docker load"; fi
  - docker build -t sails-rest-api:$TRAVIS_BUILD_NUMBER .
  - docker tag sails-rest-api:$TRAVIS_BUILD_NUMBER dmytroishchuk/sails-rest-api:$TRAVIS_BUILD_NUMBER
  - docker image ls


deploy:
  provider: script
  script: bash docker_push


script: "true"
